# vim: ft=sh
TCM_INDEX=0
GCIM_SHM_KEY="100${TCM_INDEX}"
TCMCENTER_BUS_ID="${TCM_INDEX}.0.1.1"
TCENTER_BUS_ID="${TCM_INDEX}.0.2.1"
TCONND_BUS_ID="${TCM_INDEX}.0.3.1"
TAGENT_BUS_ID="${TCM_INDEX}.0.7.1"
TCMCONSOLE_BUS_ID="${TCM_INDEX}.0.8.1"

TCENTER_LISTEN_PORT="889${TCM_INDEX}"
TCONND_LISTEN_PORT="901${TCM_INDEX}"
