
# 默认上报所有的指标数据，每条数据的说明：https://docs.tbus2.g6.woa.com/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E9%83%A8%E7%BD%B2%E8%BF%90%E7%AE%A1%E7%B1%BB/%E7%9B%91%E6%8E%A7%E4%B8%8A%E6%8A%A5/AgentMetrics%E6%8E%A5%E5%85%A5.html
# 通过正则过滤后的指标可以被http://metric_listen_url获取到，目前系统所有的指标一共约130条指标数据，每条指标有一个agent_id的默认维度。
# 业务可以通过-metric_label新增维度，新增的维度会对每一条指标生效。
# 指标采用PULL的方式拉取，拉取后，可以去Tbuspp2产品下载页面下载DashBoard和Alert模板。

# comment: key is required
+.*inq_.*
+.*outq_.*
+.*txq_.*
+.*mesh_.*
+.*step.*
+mounted_endpoint_num
+agent_num
+endpoint_num
+group_num
+poll_num
+tick_poll
+tick_output
+tick_time
+tick_misc
+pending_out_num
+ns_rpc_.*
+ns_net_fail_num
+ns_conn_fail_num
+group_traffic
+before_send_hook_cost_us
+before_routing_hook_cost_us
+before_recv_hook_cost_us
+sendback_msg_num
+otlp_.*

# 业务根据实际情况，比如自建的Prom的influxdb的内存和存储容量等因素，可以删减部分指标
# 当采集周期和重置周期（stats_update_secs）不一致时，上报 cyc_* 和 *_bucket 指标无意义，因此默认过滤

# comment: del key
-.*_bucket