# 命令行参数可以在 flags.conf 中 设置
# 每行一项配置，配置说明参考 bin/tbus2_router --help
# flags.conf 中配置可以被后面命令行参数覆盖

# support reload args

# debug/info/warn/error/fatal = 0/1/2/3/4
-log_level=1
-stderrthreshold=3

# -exit_wait_time_secs=

