/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TB_APP_TCAPLUS_H_
#define TB_APP_TCAPLUS_H_


#ifndef TDR_METALIB_TCAPLUS_TB_VERSION 
#define TDR_METALIB_TCAPLUS_TB_VERSION 	1 /*version of metalib*/
#endif

#ifndef TDR_METALIB_TCAPLUS_TB_HASH 
#define TDR_METALIB_TCAPLUS_TB_HASH 	"3761592d8ce1c5065644bd87e53c5719" /*hash of metalib*/
#endif

/*   Define c types.   */
#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
    #include <stddef.h>
    #include <time.h>
    #include <sys/types.h>

    #if !defined(_WIN32) && !defined(_WIN64)

        #include <stdint.h>
        #include <inttypes.h>

    #else /*if !defined(_WIN32) && !defined(_WIN64)*/

        //The stdint declaras
        typedef  signed char  int8_t;
        typedef  short int16_t;
        typedef  int   int32_t;
        typedef unsigned char  uint8_t;
        typedef unsigned short uint16_t;
        typedef unsigned int   uint32_t;
        #if _MSC_VER >= 1300
            typedef unsigned long long 	uint64_t;
            typedef long long 	int64_t;
        #else /* _MSC_VER */
            typedef unsigned __int64	uint64_t;
            typedef __int64	int64_t;
        #endif /* _MSC_VER */

    #endif /*if !defined(_WIN32) && !defined(_WIN64)*/

    typedef int64_t tdr_longlong;
    typedef uint64_t tdr_ulonglong;
    typedef uint16_t tdr_wchar_t;  /**<Wchar������������*/
    typedef uint32_t tdr_date_t;	/**<data������������*/
    typedef uint32_t tdr_time_t;	/**<time������������*/
    typedef uint64_t tdr_datetime_t; /**<datetime������������*/
    typedef uint32_t tdr_ip_t;  /**<IPv4��������*/
#endif /*TDR_CUSTOM_C_TYPES*/


/*   User defined includes.   */


/*   User defined macros.   */


/*   Structs/unions prototype.   */
struct tagroom_member;
typedef struct tagroom_member                                      	ROOM_MEMBER;
typedef struct tagroom_member                                      	*LPROOM_MEMBER;

struct tagroom;
typedef struct tagroom                                             	ROOM;
typedef struct tagroom                                             	*LPROOM;

struct tagbattle;
typedef struct tagbattle                                           	BATTLE;
typedef struct tagbattle                                           	*LPBATTLE;

struct taglogin;
typedef struct taglogin                                            	LOGIN;
typedef struct taglogin                                            	*LPLOGIN;

struct taguser_info;
typedef struct taguser_info                                        	USER_INFO;
typedef struct taguser_info                                        	*LPUSER_INFO;

/*   Define structs/unions.   */
#pragma pack(1)

struct tagroom_member
{
    uint64_t ullGid;                                  	/*   玩家gid(=tconnd openid) */
    uint64_t ullJoin_timestamp;                       	/*   加入时间戳(秒) */
    uint32_t dwIs_ready;                              	/*   是否准备(1=是 0=否) */
};

struct tagroom
{
    char szRoom_id[64];                               	/*   房间唯一ID(如R_00001) */
    char szRoom_name[128];                            	/*   房间名称 */
    uint64_t ullHost_gid;                             	/*   房主gid */
    uint32_t dwMax_players;                           	/*   最大人数(2-8) */
    uint32_t dwState;                                 	/*   房间状态(0=Waiting 1=InBattle) */
    char szBattle_server_address[64];                 	/*   战斗DS地址(IP:Port) */
    uint64_t ullCreated_at;                           	/*   创建时间戳(秒) */
    uint32_t dwMember_count;                          	/*   当前成员数 */
    ROOM_MEMBER astMembers[8];                        	/*   房间成员列表 */
};

struct tagbattle
{
    char szBattle_id[64];                             	/*   战斗会话唯一ID(如B_00001) */
    char szRoom_id[64];                               	/*   关联房间ID */
    char szServer_address[64];                        	/*   DS地址(IP:Port) */
    uint32_t dwPlayer_count;                          	/*   参战玩家数 */
    uint64_t players[8];                              	/*   参战玩家gid列表 */
    uint64_t ullStarted_at;                           	/*   开战时间戳(秒) */
};

struct taglogin
{
    uint64_t ullGid;                                  	/*   玩家ID(player_id) */
    uint32_t dwLogin_flag;                            	/*   登录标记 */
};

struct taguser_info
{
    uint64_t ullGid;                                  	/*   玩家ID(player_id) */
    uint32_t dwIs_new;                                	/*   是否新玩家(1=新 0=老) */
    uint32_t dwRole_type;                             	/*   用户角色类型 */
    char szUser_name[128];                            	/*   用户名称 */
    uint64_t ullPoints;                               	/*   用户积分 */
};

#pragma pack()


#endif /* TB_APP_TCAPLUS_H_ */
